*** Variables ***
${BUTTON_CHECKOUT}    id=checkout
${BUTTON_CONTINUE}    id=continue
${FIELD_FIRSTNAME}    id=first-name
${FIELD_LASTNAME}     id=last-name
${FIELD_POSTAL_CODE}  id=postal-code
${BUTTON_FINISH}      id=finish
${ELEMENT_CHECKOUT_COMPLETE}    id=checkout_complete_container
${ELEMENT_CHECKOUT_COMPLETE_TEXT}    class=complete-text
${ELEMENT_CHECKOUT_COMPLETE_HEADER}  xpath=//div[@id='checkout_complete_container']/h2
${BUTTON_BACK_HOME}    id=back-to-products

